version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  rootpassword
      MYSQL_DATABASE: ALX_prodev
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

