# Generated by Django 5.2.1 on 2025-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='users',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=models.TextField(),
        ),
    ]
